require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EarnedAwardsController do

  # This should return the minimal set of attributes required to create a valid
  # EarnedAward. As you add validations to EarnedAward, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EarnedAwardsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all earned_awards as @earned_awards" do
      earned_award = EarnedAward.create! valid_attributes
      get :index, {}, valid_session
      assigns(:earned_awards).should eq([earned_award])
    end
  end

  describe "GET show" do
    it "assigns the requested earned_award as @earned_award" do
      earned_award = EarnedAward.create! valid_attributes
      get :show, {:id => earned_award.to_param}, valid_session
      assigns(:earned_award).should eq(earned_award)
    end
  end

  describe "GET new" do
    it "assigns a new earned_award as @earned_award" do
      get :new, {}, valid_session
      assigns(:earned_award).should be_a_new(EarnedAward)
    end
  end

  describe "GET edit" do
    it "assigns the requested earned_award as @earned_award" do
      earned_award = EarnedAward.create! valid_attributes
      get :edit, {:id => earned_award.to_param}, valid_session
      assigns(:earned_award).should eq(earned_award)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new EarnedAward" do
        expect {
          post :create, {:earned_award => valid_attributes}, valid_session
        }.to change(EarnedAward, :count).by(1)
      end

      it "assigns a newly created earned_award as @earned_award" do
        post :create, {:earned_award => valid_attributes}, valid_session
        assigns(:earned_award).should be_a(EarnedAward)
        assigns(:earned_award).should be_persisted
      end

      it "redirects to the created earned_award" do
        post :create, {:earned_award => valid_attributes}, valid_session
        response.should redirect_to(EarnedAward.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved earned_award as @earned_award" do
        # Trigger the behavior that occurs when invalid params are submitted
        EarnedAward.any_instance.stub(:save).and_return(false)
        post :create, {:earned_award => {}}, valid_session
        assigns(:earned_award).should be_a_new(EarnedAward)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        EarnedAward.any_instance.stub(:save).and_return(false)
        post :create, {:earned_award => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested earned_award" do
        earned_award = EarnedAward.create! valid_attributes
        # Assuming there are no other earned_awards in the database, this
        # specifies that the EarnedAward created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        EarnedAward.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => earned_award.to_param, :earned_award => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested earned_award as @earned_award" do
        earned_award = EarnedAward.create! valid_attributes
        put :update, {:id => earned_award.to_param, :earned_award => valid_attributes}, valid_session
        assigns(:earned_award).should eq(earned_award)
      end

      it "redirects to the earned_award" do
        earned_award = EarnedAward.create! valid_attributes
        put :update, {:id => earned_award.to_param, :earned_award => valid_attributes}, valid_session
        response.should redirect_to(earned_award)
      end
    end

    describe "with invalid params" do
      it "assigns the earned_award as @earned_award" do
        earned_award = EarnedAward.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EarnedAward.any_instance.stub(:save).and_return(false)
        put :update, {:id => earned_award.to_param, :earned_award => {}}, valid_session
        assigns(:earned_award).should eq(earned_award)
      end

      it "re-renders the 'edit' template" do
        earned_award = EarnedAward.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EarnedAward.any_instance.stub(:save).and_return(false)
        put :update, {:id => earned_award.to_param, :earned_award => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested earned_award" do
      earned_award = EarnedAward.create! valid_attributes
      expect {
        delete :destroy, {:id => earned_award.to_param}, valid_session
      }.to change(EarnedAward, :count).by(-1)
    end

    it "redirects to the earned_awards list" do
      earned_award = EarnedAward.create! valid_attributes
      delete :destroy, {:id => earned_award.to_param}, valid_session
      response.should redirect_to(earned_awards_url)
    end
  end

end
